service: newsApi
frameworkVersion: "3"

plugins:
  # https://www.serverless.com/plugins/serverless-add-api-key
  - serverless-add-api-key

custom:
  apiKeys:
    - name: sampleApiKey

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x

functions:
  getNews:
    handler: handler.getNews
    events:
      - http:
          method: GET
          path: news
          private: true
